openapi: 3.0.0
info:
  title: Stamp API
  version: 1.0.0
paths:
  /stamps:
    get:
      summary: Get a list of stamps
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: The maximum number of stamps to return
        - in: query
          name: page
          schema:
            type: integer
          description: The page number of stamps to return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStampResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
  /stamps/{id}:
    get:
      summary: Get a stamp by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the stamp
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdResponseBody'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
components:
  schemas:
    BlockRow:
      type: object
      properties:
        block_index:
          type: integer
        block_hash:
          type: string
        block_time:
          oneOf:
            - type: integer
            - type: string
              format: date-time
        previous_block_hash:
          type: string
        difficulty:
          type: number
        ledger_hash:
          type: string
        txlist_hash:
          type: string
        messages_hash:
          type: string
        indexed:
          type: integer
        issuances:
          type: integer
        sends:
          type: integer
    StampRow:
      type: object
      properties:
        stamp:
          oneOf:
            - type: integer
        block_index:
          type: integer
        cpid:
          type: string
        asset_longname:
          oneOf:
            - type: string
        creator:
          type: string
        divisible:
          type: number
        keyburn:
          oneOf:
            - type: number
        locked:
          type: number
        message_index:
          type: integer
        stamp_base64:
          type: string
        stamp_mimetype:
          type: string
        stamp_url:
          type: string
        supply:
          type: number
        timestamp:
          type: string
          format: date-time
        tx_hash:
          type: string
        tx_index:
          type: integer
        src_data:
          type: string
        ident:
          type: string
          enum:
            - STAMP
            - SRC-20
            - SRC-721
        creator_name:
          oneOf:
            - type: string
        stamp_gen:
          type: string
        stamp_hash:
          type: string
        is_btc_stamp:
          type: integer
        is_reissue:
          oneOf:
            - type: integer
        file_hash:
          type: string
    SendRow:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        cpid:
          oneOf:
            - type: string
        tick:
          oneOf:
            - type: string
        memo:
          type: string
        quantity:
          type: string
          format: int64
        tx_hash:
          type: string
        tx_index:
          type: integer
        block_index:
          type: integer
    HolderRow:
      type: object
      properties:
        address:
          type: string
        quantity:
          type: number
        divisible:
          type: number
    BlockInfo:
      type: object
      properties:
        block_info:
          $ref: '#/components/schemas/BlockRow'
        issuances:
          type: array
          items:
            $ref: '#/components/schemas/StampRow'
        sends:
          type: array
          items:
            $ref: '#/components/schemas/SendRow'
    XCPParams:
      type: object
      properties:
        filters:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              op:
                type: string
              value:
                type: string
        address:
          type: string
        asset:
          type: string
    SRC20Balance:
      type: object
      properties:
        id:
          type: string
        address:
          type: string
        cpid:
          type: string
        p:
          type: string
        tick:
          type: string
        amt:
          type: number
        block_time:
          type: string
          format: date-time
        last_update:
          type: number
    PaginationQueryParams:
      type: object
      properties:
        limit:
          type: integer
        page:
          type: integer
    PaginatedRequest:
      type: object
      properties:
        query:
          $ref: '#/components/schemas/PaginationQueryParams'
    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        totalPages:
          type: integer
        total:
          type: integer
    PaginatedStampResponseBody:
      type: object
      properties:
        last_block:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/StampRow'
        pagination:
          $ref: '#/components/schemas/Pagination'
    IdResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/StampRow'
        last_block:
          type: integer
    PaginatedIdResponseBody:
      type: object
      properties:
        ident:
          oneOf:
            - type: string
        last_block:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/StampRow'
        pagination:
          $ref: '#/components/schemas/Pagination'
    ErrorResponseBody:
      type: object
      properties:
        error:
          type: string
